export class Cartitems {

    categories=["Games","Fruits","Nuts","Biscuit","Veg"];

    Games:Array<any>=[
        {
          "name":"Fortnite",
          "clas":"Game",
          "price":500,
          "incart":false
        },
        {
          "name":"Pubg",
          "clas":"Game",
          "price":400,
          "incart":false
        },
        {
          "name":"CSGO",
          "clas":"Game",
          "price":650,
          "incart":false
        },
        {
          "name":"Overwatch",
          "clas":"Game",
          "price":600,
          "incart":false
        },
        {
          "name":"Naruto",
          "clas":"Game",
          "price":200,
          "incart":false
        },
        {
          "name":"DOTA",
          "clas":"Game",
          "price":1000,
          "incart":false
        },
        {
          "name":"Battlefield",
          "clas":"Game",
          "price":1200,
          "incart":false
        },
        {
          "name":"MaxPayne",
          "clas":"Game",
          "price":1000,
          "incart":false
        },
        {
          "name":"Tekken",
          "clas":"Game",
          "price":500,
          "incart":false
        },
        {
          "name":"GTA",
          "clas":"Game",
          "price":1200,
          "incart":false
        },
      ]
    
       Fruits:Array<any>=[
        {
            "name":"Mango",
            "clas":"Fruit",
            "price":100,
            "incart":false
        },
        {
            "name":"Apple",
            "clas":"Fruit",
            "price":120,
            "incart":false
        },
        {
            "name":"Kiwi",
            "clas":"Fruit",
            "price":150,
            "incart":false
        },
        {
            "name":"Banana",
            "clas":"Fruit",
            "price":50,
            "incart":false      
        },
        {
            "name":"Guava",
            "clas":"Fruit",
            "price":60,
            "incart":false      
        },
        {
            "name":"Orange",
            "clas":"fruit",
            "price":80,
            "incart":false       
        },
        {
            "name":"Watermelon",
            "clas":"Fruit",
            "price":40,
            "incart":false    
        },
        {
            "name":"Melon",
            "clas":"Fruit",
            "price":50,
            "incart":false     
        },
        {
            "name":"Apricot",
            "clas":"Fruit",
            "price":120,
            "incart":false      
        },
        {
            "name":"Grapes",
            "clas":"fruit",
            "price":70,
            "incart":false     
        },
    ]
    
     Nuts:Array<any>=[
       
      {
        "name":"Almonds",
        "class":"nut",
        "price":1000,
        "incart":false
      },
      {
        "name":"Pistachio",
        "class":"nut",
        "price":800,
        "incart":false
      },
      {
        "name":"Cashew",
        "class":"nut",
        "price":900,
        "incart":false
      },
      {
        "name":"Hazelnut",
        "class":"nut",
        "price":1000,
        "incart":false
      },
      {
        "name":"Walnut",
        "class":"nut",
        "price":1000,
        "incart":false
      }
     ]
    
     Veg:Array<any>=[
        {
            "name":"Potato",
            "clas":"Vegetable",
            "price":40,
            "incart":false
        },
        {
            "name":"Tomato",
            "clas":"Vegetable",
            "price":50,
            "incart":false
        },
        {
            "name":"Onion",
            "clas":"Vegetable",
            "price":60,
            "incart":false
        },
        {
            "name":"Brinjal",
            "clas":"Vegetable",
            "price":30,
            "incart":false
        },
        {
            "name":"Cabbage",
            "clas":"Vegetable",
            "price":40,
            "incart":false
        },
        {
            "name":"Beans",
            "clas":"Vegetable",
            "price":40,
            "incart":false
        },
        {
            "name":"Gourd",
            "clas":"Vegetable",
            "price":30,
            "incart":false
        },
        {
            "name":"Ladyfinger",
            "clas":"Vegetable",
            "price":40,
            "incart":false
        },
        {
            "name":"Bitter-Gourd",
            "clas":"Vegetable",
            "price":50,
            "incart":false
        }
    ]
    
     Biscuit:Array<any>=[
        {
            "name":"ParleG",
            "clas":"Biscuit",
            "price":10,
            "incart":false
        },
        {
            "name":"Oreo",
            "clas":"Biscuit",
            "price":25,
            "incart":false
        },
        {
            "name":"Burboun",
            "clas":"Biscuit",
            "price":20,
            "incart":false
        },
        {
            "name":"Britania",
            "clas":"Biscuit",
            "price":15 ,
            "incart":false       
        },
        {
            "name":"Mario",
            "clas":"Biscuit",
            "price":15,
            "incart":false
    
        },
        {
            "name":"Dark-Fantasy",
            "clas":"Biscuit",
            "price":30,
            "incart":false
        },
        {
            "name":"Tiger",
            "clas":"Biscuit",
            "price":10,
            "incart":false
        },
        {
            "name":"50-50",
            "clas":"Biscuit",
            "price":10,
            "incart":false
    
        }
    ]
    
    all=[this.Games,this.Biscuit,this.Fruits,this.Nuts,this.Veg];
    
}

